name: Receive and Schedule Message

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Time to send message (format: HH:MM AM/PM, e.g., 01:30 PM)'
        required: true
        default: '12:00 PM'
      message:
        description: 'Message to send'
        required: true
        default: 'Default message'

jobs:
  schedule-message:
    runs-on: ubuntu-latest
    steps:
    - name: Calculate schedule time
      id: calculate-time
      run: |
        python << EOF
        from datetime import datetime, timedelta
        import os

        def parse_time(time_str):
            now = datetime.now()
            parsed_time = datetime.strptime(time_str, "%I:%M %p")
            schedule_time = now.replace(hour=parsed_time.hour, minute=parsed_time.minute, second=0, microsecond=0)

return schedule_time

            
        
        EOF

    - name: Schedule repository dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: ${{ github.event.inputs.message }}
      run: |
        schedule_time="${{ steps.calculate-time.outputs.schedule_time }}"
        current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        delay_seconds=$(( $(date -d "$schedule_time" +%s) - $(date -d "$current_time" +%s) ))
        
        if [ $delay_seconds -le 0 ]; then
          echo "Scheduled time is in the past. Triggering immediately."
          delay_seconds=0
        fi
        
        echo "Scheduling message to be sent after $delay_seconds seconds"
        
        (sleep $delay_seconds && \
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "send_telegram_message", "client_payload": {"message": "'"$MESSAGE"'"}}') &
        
        echo "Repository dispatch scheduled"
