name: Receive and Schedule Message

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Time to send message (format: HH:MM AM/PM, e.g., 01:30 PM)'
        required: true
        default: '12:00 PM'
      message:
        description: 'Message to send'
        required: true
        default: 'Default message'

jobs:
  schedule-message:
    runs-on: ubuntu-latest
    steps:
    - name: Calculate schedule time
      id: calculate-time
      run: |
        python << EOF
        from datetime import datetime, timedelta
        import pytz
        
        def parse_time(time_str):
            now = datetime.now(pytz.utc)
            parsed_time = datetime.strptime(time_str, "%I:%M %p")
            schedule_time = now.replace(hour=parsed_time.hour, minute=parsed_time.minute, second=0, microsecond=0)
            if schedule_time < now:
                # If the scheduled time is in the past, schedule it for the next day
                schedule_time += timedelta(days=1)
            return schedule_time
        
        time_str = "${{ github.event.inputs.time }}"
        schedule_time = parse_time(time_str)
        print(f"::set-output name=schedule_time::{schedule_time.isoformat()}")
        EOF

    - name: Wait until scheduled time
      id: wait-until-time
      run: |
        schedule_time="${{ steps.calculate-time.outputs.schedule_time }}"
        echo "Scheduled time: $schedule_time"
        while [ "$(date -u +%Y-%m-%dT%H:%M:%S)" != "$(date -u -d "$schedule_time" +%Y-%m-%dT%H:%M:%S)" ]; do
          sleep 1
          current_time=$(date -u +%Y-%m-%dT%H:%M:%S)
          echo "Current time (UTC): $current_time"
          if [ "$current_time" \> "$schedule_time" ]; then
            echo "Current time has surpassed scheduled time, breaking loop."
            break
          fi
        done

    - name: Trigger repository dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: ${{ github.event.inputs.message }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "send_telegram_message", "client_payload": {"message": "'"$MESSAGE"'"}}'
        echo "Repository dispatch triggered"
