name: Send Telegram Message

on:
  repository_dispatch:
    types: [send_telegram_message]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram message
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        MESSAGE=$(echo "${{ github.event.client_payload.message }}" | jq -sRr @uri)
        curl -X GET "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=5616711824&text=$MESSAGE"
